[colors.primary]
background = '{{colors.background.default.hex}}'
foreground = '{{colors.on_surface.default.hex}}'

[colors.selection]
text = '{{colors.on_surface.default.hex}}'
background = '{{colors.primary_container.default.hex}}'

[colors.cursor]
text = '{{colors.background.default.hex}}'
cursor = '{{colors.primary.default.hex}}'

[colors.normal]
black   = '{{dank16.color0.default.hex}}'
red     = '{{dank16.color1.default.hex}}'
green   = '{{dank16.color2.default.hex}}'
yellow  = '{{dank16.color3.default.hex}}'
blue    = '{{dank16.color4.default.hex}}'
magenta = '{{dank16.color5.default.hex}}'
cyan    = '{{dank16.color6.default.hex}}'
white   = '{{dank16.color7.default.hex}}'

[colors.bright]
black   = '{{dank16.color8.default.hex}}'
red     = '{{dank16.color9.default.hex}}'
green   = '{{dank16.color10.default.hex}}'
yellow  = '{{dank16.color11.default.hex}}'
blue    = '{{dank16.color12.default.hex}}'
magenta = '{{dank16.color13.default.hex}}'
cyan    = '{{dank16.color14.default.hex}}'
white   = '{{dank16.color15.default.hex}}'
